name: hotel_choosing
description: Hotel Selection Apps.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^10.1.2
  flutter_hooks: ^0.20.1
  flutter_dotenv: ^5.1.0
  intl: ^0.18.1
  retrofit: ^4.0.1
  logger: ^2.0.1
  dio: ^5.3.2
  json_annotation: ^4.8.1
  flutter_svg: ^2.0.7
  sprung: ^3.0.1
  hooks_riverpod: ^2.3.10
  mask_text_input_formatter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  go_router_builder: ^2.3.1
  build_runner: ^2.4.6
  build_verify: ^3.1.0
  retrofit_generator: ^7.0.8
  json_serializable: ^6.7.1

flutter:
  generate: true
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/

  fonts:
    - family: SF UI Display
      fonts:
        - asset: fonts/sf_pro_display_semibold.ttf
          weight: 600
        - asset: fonts/sf_pro_display_medium.ttf
          weight: 500
        - asset: fonts/sf_pro_display_regular.ttf
          weight: 400